ERROR TO SOLVE
WITH TYPES_CHECK = TRUE (IMPORTANT) after creating and trying to insert into a table with Decimal128(12) columns, an error is catched and execution stops because:
class Decimal128 doesn't assign an int_size, so when max_signed_int is to be calculated, it will multiply 8*None. 

ERROR
File "/usr/local/lib/python3.9/site-packages/clickhouse_driver/columns/decimalcolumn.py", line 19, in __init__
    max_signed_int = (1 << (8 * self.int_size - 1)) - 1
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'


How can we solve this?